###########################################################
#░██████╗███╗░░░███╗██████╗░░░░░░░░########################
#██╔════╝████╗░████║██╔══██╗░░██╗░░########################
#╚█████╗░██╔████╔██║██████╔╝██████╗## 𝑨𝒖𝒕𝒉𝒐𝒓: 𝑺𝒄𝒂𝒍𝒆𝒓𝑮𝒂𝒎𝒆𝒔 ##
#░╚═══██╗██║╚██╔╝██║██╔═══╝░╚═██╔═╝## 𝑪𝒐𝒏𝒇𝒊𝒈 𝑽𝒆𝒓𝒔𝒊𝒐𝒏: 1.0 ##
#██████╔╝██║░╚═╝░██║██║░░░░░░░╚═╝░░########################
#╚═════╝░╚═╝░░░░░╚═╝╚═╝░░░░░░░░░░░░########################
###########################################################

Events:
  Chat:
    enabled: true
    format: "{displayname} &8&l» &r{message}"
  Join:
    enabled: true
    message: "&8&l[&2▶&8&l] &aWelcome {player} back to the server"
  FirstJoin:
    enabled: true
    message: "&8&l[&3ⓌⒺⓁⒸⓄⓂⒺ&8&l] &3{player} joined the server for the first time"
  Quit:
    enabled: true
    message: "&8&l[&c◀&8&l] &d{player} left the server"
  Death:
    enabled: true
    message: "&8&l[&c☠&8&l] &c{message}"
  Sleep:
    single-player-sleep: true
    message: "&8&l[&e☼&8&l]&8&l &e{player} has slept the night away"
  MobDeath:
    ENDER_DRAGON:
      message: "{player} killed the Ender Dragon!"

Commands:
  rules:
    method: GUI
    gui-name: rules
  help:
    method: GUI
    gui-name: help

ItemFrames:
  Range:
    X: 3.0
    Y: 3.0
    Z: 3.0

Shulkers:
  Respawn: true
  Chance: 0.3