###########################################################
#░██████╗███╗░░░███╗██████╗░░░░░░░░########################
#██╔════╝████╗░████║██╔══██╗░░██╗░░########################
#╚█████╗░██╔████╔██║██████╔╝██████╗## 𝑨𝒖𝒕𝒉𝒐𝒓: 𝑺𝒄𝒂𝒍𝒆𝒓𝑮𝒂𝒎𝒆𝒔 ##
#░╚═══██╗██║╚██╔╝██║██╔═══╝░╚═██╔═╝## 𝑪𝒐𝒏𝒇𝒊𝒈 𝑽𝒆𝒓𝒔𝒊𝒐𝒏: 1.0 ##
#██████╔╝██║░╚═╝░██║██║░░░░░░░╚═╝░░########################
#╚═════╝░╚═╝░░░░░╚═╝╚═╝░░░░░░░░░░░░########################
###########################################################

Events:
  Chat:
    enabled: true
    format: "{displayname} &8&l» &r{message}"
  Join:
    enabled: true
    message: "&8&l[&2▶&8&l] &aWelcome {player} back to the server"
  FirstJoin:
    enabled: true
    message: "&8&l[&3ⓌⒺⓁⒸⓄⓂⒺ&8&l] &3{player} joined the server for the first time"
  Quit:
    enabled: true
    message: "&8&l[&c◀&8&l] &d{player} left the server"
  Death:
    enabled: true
    message: "&8&l[&c☠&8&l] &c{message}"
  Sleep:
    single-player-sleep: true
    message: "&8&l[&e☼&8&l]&8&l &e{player} has slept the night away"
  MobDeath:
    ENDER_DRAGON:
      message: "{player} killed the Ender Dragon!"
  PlayerDropHead:
    enabled: false
    place-in-inventory: false
    message: "&2You got a player head"

Commands:
  rules:
    method: GUI
    gui-name: rules
  help:
    method: GUI
    gui-name: help

Durability:
  enabled: true
  message: "&8&l[&c⛏&8&l] &cThe item (&c&n{item}&c) has low durability!"
  amount: 8

ItemFrames:
  Range:
    X: 3.0
    Y: 3.0
    Z: 3.0

CraftingRecipes:
  bundle:
    result:
      item: 'BUNDLE'
    shape:
      row_1: "AAA"
      row_2: "ABA"
      row_3: "AAA"
    materials: ['LEATHER', 'CHEST']
  name_tag:
    result:
      item: 'NAME_TAG'
    shape:
      row_1: "ABA"
      row_2: "CDC"
      row_3: "CDC"
    materials: ['IRON_INGOT', 'STRING', 'IRON_BLOCK', 'PAPER']

Shulkers:
  Respawn: true
  Chance: 0.3

TerracottaRotator:
  item: 'STICK'
  display_name: '&6&lTerracotta Rotator'

CustomEvents:
  main-command:
    messages:
      - '&8&l[&3〓&8&l] &cThere is no event on right now'
  sub-commands:
    announce:
      commands:
        - 'broadcast chat &cHello'
