main: Dev.ScalerGames.SmpPlus.Main
name: SmpPlus
version: 1.0.0-BETA-2
api-version: 1.13
author: ScalerGames
description: The Official SmpPlus Plugin For Minecraft
loadbefore:
  - Essentials
softdepend:
  - PlaceholderAPI
  - Vault
  - HeadDatabase
  - Essentials
commands:
  itemframe:
  smp:
  nickname:
  itemname:
  itemlore:
  rules:
  help: